Prevent capture and performance counter when idle
any1/wayvnc pull request #150
Opened 2022-08-19 01:03 UTC by Consolatis

Fixes
- #80

I have read and understood CONTRIBUTING.md

This includes a condition `if (!self->nr_clients)` instead of `if (self->nr_clients == 0)`, will change if you prefer it to be more explicit.

2022-08-20 11:52 UTC, any1 requested changes

2022-08-20 11:52 UTC, any1 commented on src/main.c
> +	self->performance_ticker = aml_ticker_new(1000, on_perf_tick, self, NULL);
It's possible to restart a ticker, so it doesn't really need to be reinitialised; just created during init and then started/stopped. Not sure if would make the code simpler or shorter though. You can explore that avenue if you want.

2022-08-20 11:52 UTC, any1 commented on src/main.c
> +		nvnc_log(NVNC_LOG_INFO, "Stopping screencopy");
Maybe say "Stopping screen capturing" instead? "screencopy" is an implementation detail.

2022-08-20 11:52 UTC, any1 commented on src/main.c
> +	if (!self->nr_clients) {
Yeah, this project uses `!` for boolean expressions and `NULL` pointer checks.

2022-08-20 11:52 UTC, any1 commented on src/main.c
> +		nvnc_log(NVNC_LOG_INFO, "Starting screencopy");
Same as above regarding "screencopy"

2022-08-20 14:31 UTC, Consolatis commented on src/main.c
> +	self->performance_ticker = aml_ticker_new(1000, on_perf_tick, self, NULL);
Changed, ticker is created in `main()` and `aml_unref()`ed in `wayvnc_destroy()`.
Additional benefit: the `perfomance_show` boolean in `struct wayvnc` has been removed.

2022-08-20 14:36 UTC, Consolatis commented on src/main.c
> +		wl_display_dispatch(self.display);
Force pushed the next iteration:
- Review comments should all be addressed
- Added a check for `disable_input` before `wl_display_dispatch()` in `main()` because it was hanging when starting with `--disable-input` when delaying start of the capture until a client connects

2022-08-21 11:47 UTC, any1 commented on src/main.c
> +		wl_display_dispatch(self.display);
The role of this is to dispatch pending events before blocking. I suppose that without input initialisation, there are no remaining events at that point. A more robust way to do this would be to use `wl_display_dispatch_pending()` since that won't block when there are no events.

2022-08-21 12:09 UTC, Consolatis commented on src/main.c
> +		wl_display_dispatch(self.display);
Replaced with `wl_display_dispatch_pending()`

2022-08-21 14:06 UTC, any1 commented on src/main.c
> +		wl_display_dispatch(self.display);
Actually, that comment is misleading. It should always have been `wl_display_dispatch_pending()`. The purpose of calling it there is to dispatch any pending events before waiting for new ones. The `aml_poll()` won't detect pending wayland events that have already been read from the socket, so this is there to make sure that they're all handled before blocking. Once inside the main loop, events are handled by `on_wayland_event()` before blocking next time.

2022-08-21 14:13 UTC, Consolatis commented on src/main.c
> +		wl_display_dispatch(self.display);
Should I remove the comment completely or change into something like
> Make sure all pending events are handled

2022-08-21 14:15 UTC, any1 commented on src/main.c
> +		wl_display_dispatch(self.display);
Yeah, it doesn't need a comment.

2022-08-21 14:30 UTC, Consolatis commented on src/main.c
> +		wl_display_dispatch(self.display);
deleted the comment

2022-08-21 16:29 UTC, merged

2022-08-21 16:29 UTC, any1 commented
Thanks!