More INFO-level logging
any1/wayvnc pull request #162
Opened 2022-10-09 03:06 UTC by lack

Adds more output to verbose mode, including:
- Log the listening address and port
- Log removal of seats and outputs
- Add manpage section about multiple outputs
- Log signal handler
- Log output selection and list of outputs

2022-10-09 10:22 UTC, any1 requested changes
Looks mostly good. Did you read contributing.md?

2022-10-09 10:22 UTC, any1 commented on src/main.c
> +				(output->id == self->selected_output->id) ? ">>" : "--",
Consider putting the result of this expression into an intermediate variable so that this can be wrapped within the 80 column limit.

I think it would probably look nicer to use `? "*" : " "`.

2022-10-10 06:28 UTC, lack commented on src/main.c
> +				(output->id == self->selected_output->id) ? ">>" : "--",
I did try `? "*" : " "` but since nvnv_log(...) eats all leading spaces, the alignment didn't work.

2022-10-10 08:25 UTC, any1 commented on src/main.c
> +				(output->id == self->selected_output->id) ? ">>" : "--",
Ahh. There were some unruly messages coming from ffmpeg. Maybe trimming of leading whitespace was not actually needed. We'll fix it later.

2022-10-10 08:28 UTC, merged

2022-10-10 08:28 UTC, any1 commented
Thanks!