Multi-output: keybind to cycle between outputs
any1/wayvnc pull request #163
Opened 2022-10-11 13:12 UTC by lack

In support of multi-outout displays (#112), this changeset primarily adds three things to wayvnc:
1. Internal refactoring to support switching capture and pointer input to other outputs while a client is connected
2. A general feature to define wayvnc keyboard shortcuts
3. A commandline option to configure a keyboard shortcut which cycles through multiple outputs.

The end result is that when I have multiple outputs
configured and I start `wayvnc -S ctrl+alt+tab ...`
wayvnc starts up normally and a connected client sees
and interacts with only the first output. Then when I
press `ctrl+alt+tab` in the client, the view switches
to the 2nd output and the pointer moves over to match.
Pressing `ctrl+alt+tab` again would move on to the
next output, or cycle back to the 1st one if we're on
the last one.

I have read and understood CONTRIBUTING.md and its associated documents.

2022-10-11 22:29 UTC, any1 requested changes

2022-10-11 22:29 UTC, any1 commented on src/output.c
> +struct output* output_next(const struct wl_list* list,
Maybe this should be called something like `output_cyclic_next`, so that it's easier to infer the semantics without looking at the function definition.

2022-10-11 23:52 UTC, lack commented on src/main.c
> +	struct nvnc_fb* placeholder_fb =
Gotcha.  I'll try without this.  My first attempts didn't refresh the whole screen. But maybe the stop capture/start capture I added later are now sufficient?

2022-10-11 23:54 UTC, lack commented on src/output.c
> +static inline struct output* output_iter(const struct wl_list* list,
It saves me from duplicating the nearly-identical code in each, with `inline` so it's the compiler and not me that does the duplication.

Point taken about the `wrap` arg.  That is leftover from some other refactoring.

2022-10-11 23:56 UTC, lack commented on src/output.c
> +struct output* output_next(const struct wl_list* list,
I guess I could explicitly put the `wrap` arg in the signature here so it's opt-in?

2022-10-12 00:44 UTC, lack commented on src/main.c
> +	struct nvnc_fb* placeholder_fb =
Confirmed: not needed at all for output cycling!

2022-10-12 00:45 UTC, lack commented on src/output.c
> +static inline struct output* output_iter(const struct wl_list* list,
I think I found a better API for this.  Standby.

2022-10-12 00:45 UTC, lack commented on src/output.c
> +struct output* output_next(const struct wl_list* list,
Deprecated by my better API coming soon.

2022-10-12 09:02 UTC, any1 approved these changes
LGTM. I'll merge this with part 2.

2022-10-12 09:02 UTC, any1 commented on src/output.c
> +	return wl_container_of(iter, output, link);
I think you can just as well say `wl_container_of(iter, struct output, link)` here.

2022-11-06 14:55 UTC, merged

2022-11-06 14:56 UTC, any1 commented
Thanks!