wayvncctl
any1/wayvnc pull request #171
Opened 2022-10-31 00:41 UTC by lack

- Refactor pointer initialization code
- Refactor output selection code
- Add output_cycle to get next/prev outputs
- Add functions to switch outputs on the fly
- Switch to previous output if current output disappears
- Add json-ipc message plumbing
- Add ctl control socket and initial command infrastructure
- Refactor some common utilities out of main
- Add ctl-client code
- Add initial wayvncctl executable
- Add wayvnctl help command
- Add wayvncctl version command

Note: still needs a manpage for wayvncctl and doc updates

I have read and understood CONTRIBUTING.md and its associated documents.

2022-10-31 23:03 UTC, any1 requested changes
The quality here is well above average when it comes to code I've reviewed for this project.

I did not have time today to look at this as thoroughly as I would have liked and I may have missed important details.

Overall, I would like to see the log level dropped a little bit. There is an `nvnc_trace()` macro which I feel is underutilised.

2022-10-31 23:55 UTC, lack commented on src/ctl-server.c
> +		strncpy(cmd->target, target, sizeof(cmd->target));
Sure!  What's the difference?

2022-11-01 09:55 UTC, any1 commented on src/ctl-server.c
> +		strncpy(cmd->target, target, sizeof(cmd->target));
`strncpy` will omit the null-terminator if the length of the source string exceeds the size argument. `strlcpy` always null-terminates.

2022-11-01 09:58 UTC, any1 commented on src/ctl-server.c
> +		strncpy(cmd->target, target, sizeof(cmd->target));
`strlcpy` has its downsides as well though, but we're using it for now: https://lwn.net/Articles/905777/

2022-11-01 11:49 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
For now the pattern is that the client expects to read exactly one json response and then discard the rest, so the json parentheses `{...}` are the delimiter.

I totally agree that when we implement server->client events and the client needs to accept multiple json objects, we'll want something more robust like the ctl-server.c receive loop which does a nice job of handling partial reads and waiting for complete json objects to arrive.

Fixed the `sizeof(buffer)` issue.

2022-11-01 12:53 UTC, any1 commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
I see, you run the json parser on the input until it completes and then you save the pointer to the error position, where it started to receive something unexpected after parsing the object.

Is it possible for this mechanism to enter a bad state? What happens if the user inputs an opening bracket that never gets closed? Will the connection recover at some point?

2022-11-01 13:04 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
I go one step further and purge anything at the start of the input that's not `{`, too.

But the limit case here is as you say: input that starts like a valid json object but never gets to a full object.

```
{"infinitely long string goes here...
```

I handle that by just dropping the connection if we completely fill the receive buffer without ever seeing a json object.

2022-11-01 13:05 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
Idea being that a client who is that rude isn't one we want to talk to anyway :)

2022-11-01 13:09 UTC, lack commented on src/ctl-client.c
> +	for(int i = 1; i < argc; ++i) {
So instead of

```
wayvncctl methodname paramname1=value paramname2=value
```

We want

```
wayvncctl methodname --paramname1[= ]value --paramname2[= ]value
```

That's probably not hard, and I like that idea?

2022-11-01 16:32 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
I guess I figure when the message format already has a clear start and end point, adding an additional delimiter doesn't gain us much...

So what about this edge case where a client has sent a partial message and wants to give up after a partial transmission?

- A client could simply disconnect and reconnect.
- A client could send something that's guaranteed to cause the parser to give up and discard what's partly sent. Like maybe `",\0` Needs some experimentation.
- Or we could just decide on a reset token like `\0\0\0` that forcibly clears and pending buffer.  But it doesn't need to be sent after every message; just to flush a weird error.

2022-11-01 16:42 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
And I would hope any interactive cli worth its salt would do local editing and at least a "is this valid json" sanity check before sending any data.

Even socat in "readline" mode works like that.

2022-11-01 19:02 UTC, any1 commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
Don't you think that it would be simpler to just use a delimiter? I agree that using a delimiter would be redundant, but redundancy in communication protocols is often good. In this case, it just makes everything clear an precise.

The current method works and I don't really have a concrete argument against it, so if you really, really, want to keep it this way, I'm not going to argue any more, but it smells kinda funky to me. :)

Either way, I don't think it's a good idea to allow garbage between messages. They should just be clear-cut and garbage should result in closed connection. It's better to fail fast.

2022-11-01 22:40 UTC, lack commented on src/ctl-client.c
> +	for(int i = 1; i < argc; ++i) {
Okay!  Updated to do this now!

2022-11-06 02:02 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
After our conversation on IRC, I have more formally delineated a few error scenarios that drop the connection:
- read failure
- if the json parser rejects the input as invalid json (except the `json_error_premature_end_of_input` which means we wait for more input)
- if we fill the read buffer before we get to a full valid json object

As long as what we get is one or more valid json objects, any error beyond that returns an error object but does not drop the connection.

2022-11-06 02:09 UTC, lack commented on wayvncctl.scd
> +{
Okay!  Here's what I've got now:

- Special case for `wayvncctl $name --help` that is equivalent to `wayvncctl help --command=$name`
- Default output is a pretty-printer that does per-command human-readable output
- Optional `--json` flag which produces json to stdout for machine consumption
- Guarantee that warning and debug output go to stderr so only the command result (or json) goes to stdout

I think I'm pretty happy with how it looks now.  See `wayvncctl.scd` at the branch head for an example of the new pretty-printer output.

2022-11-06 02:20 UTC, lack commented on wayvncctl.scd
> +{
The one thing I didn't change was the way `wayvncctl --help` works...  So:

- `wayvncctl --help` shows the syntax for the wayvncctl command itself. Purely "local" in that it doesn't touch the control socket.
- `wayvncctl help` or `wayvncctl $name --help` interact with the control socket and query the actual command info as defined by the server.

2022-11-06 14:48 UTC, any1 commented on wayvncctl.scd
> +{
Getting the help text from the server is a nice feature for a remote REST service on the internet. But isn't it overkill for this? I mean, the utility for chatting with the server is a part of the same git repo, so it has all the same info as the server.

Not being able to use the help unless the server is running is slightly sub-optimal.

Would it not be simpler to just use `getopt_long` for option parsing and hardcoding commands and help texts into `wayvncctl`? It avoids having to implement a custom option parser that probably does not entirely conform to people's expectations.

2022-11-06 16:05 UTC, any1 requested changes

2022-11-06 16:09 UTC, any1 commented on wayvncctl.scd
> +{
Keeping the documentation and the command structure on the server side might help with code organisation and keeping down duplication. I'm not strictly against it; just wondering if the "boring" alternative might be better.

2022-11-07 00:52 UTC, lack commented on src/ctl-client.c
> +#define WARN(fmt, args...) \
I think it's a GNU CPP extension.  I like it better. But can change it back if you prefer something more standard-compliant.

2022-11-07 00:58 UTC, lack commented on src/util.c
> +const char* wayvnc_version =
I moved this so it's available to both the `wayvnc` and `wayvncctl` executables.

2022-11-07 01:00 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
Yeah. I suppose so.  In my testing it's always received the whole response at once. But I agree it's not guaranteed.

2022-11-07 01:01 UTC, lack commented on src/ctl-server.c
> +		ssize_t n = send(client->fd, buffer, len, MSG_NOSIGNAL);
Indeed.  I was actually hoping there would be something like stream.c but generic I could reuse for this.  Seems like something maybe AML could provide as part of its value-add :)

2022-11-07 01:07 UTC, lack commented on src/ctl-server.c
> +	nvnc_log(NVNC_LOG_INFO, "Listening for wayvncctl commands on %s", self->socket_path);
I think it's valuable for users to know where the control socket is.  The default is to try `$XDG_RUNTIME_DIR` and if that's not set fall back to `/tmp`, but it's also settable via the command line.

I like the clarity of a quick "where did I put that" in the info log.

2022-11-07 01:22 UTC, lack commented on src/ctl-server.c
> +		json_t* item = json_array_get(client->response_queue, 0);
Is it okay for me to leave this flow as-is?  That is, enqueue the response and wait on write-ready to send it, assuming I add in the fix for incomplete writes, that is?

2022-11-07 09:13 UTC, any1 commented on src/ctl-server.c
> +	nvnc_log(NVNC_LOG_INFO, "Listening for wayvncctl commands on %s", self->socket_path);
If you're running from within sway you probably have `XDG_RUNTIME_DIR` set, so most of the time, this will just be noise.

However, it might warrant a warning if `XDG_RUNTIME_DIR` isn't set and you need to fall back to `/tmp`. That way the user's attention is more likely drawn to the problem.

2022-11-07 09:13 UTC, any1 commented on src/util.c
> +const char* wayvnc_version =
ok

2022-11-07 09:24 UTC, any1 commented on src/ctl-server.c
> +		ssize_t n = send(client->fd, buffer, len, MSG_NOSIGNAL);
It's out-of-scope for aml, but it is tempting to add something like that. Maybe, I could have it separate from the main interface and put it into `aml-stream.h` or something like that..

2022-11-07 09:27 UTC, any1 commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
For such small reads and writes, I suspect that you won't ever run into any issues with this, even on a heavily loaded system, but it's still always better to be "to spec".

2022-11-07 09:30 UTC, any1 commented on src/ctl-server.c
> +		json_t* item = json_array_get(client->response_queue, 0);
Sure, I suppose that this can also be used as a deferred write mechanism, so maybe it's better this way. But, this should still be its own function. I like small functions. They aide readability.

2022-11-07 09:31 UTC, any1 commented on src/ctl-client.c
> +#define WARN(fmt, args...) \
Standard compliant, please. :)

2022-11-08 00:35 UTC, lack commented on src/ctl-client.c
> +	int n = read(self->fd, buf, 512);
I think my latest update is on spec, better, and future-proof for when I introduce "listen for events mode"

2022-11-08 00:35 UTC, lack commented on src/ctl-server.c
> +		json_t* item = json_array_get(client->response_queue, 0);
Split the functions.  Much cleaner!

2022-11-08 10:07 UTC, any1 commented on src/wayvncctl.c
> +void wayvncctl_exit(struct wayvncctl* self)
This doesn't seem to do anything.

2022-11-08 12:27 UTC, lack commented on src/ctl-client.c
> +		int n = poll(&pfd, 1, timeout_ms);
I was intending the timeout to be per-partial-read-attempt, not global across all read-chunks.

2022-11-08 12:29 UTC, lack commented on src/wayvncctl.c
> +void wayvncctl_exit(struct wayvncctl* self)
Good catch! Left-over from refactoring :). Will remove.

2022-11-08 12:42 UTC, any1 commented on src/ctl-client.c
> +		int n = poll(&pfd, 1, timeout_ms);
A particularly poor server implementation could make the client stall for `timeout_ms * 512 ms` but that's not really a concern. :p

2022-11-08 13:45 UTC, lack commented on src/ctl-server.c
> +	while((root = client_next_object(client, &details)) != NULL) {
I always fear that `while (true)` will bite me someday... But I'm happy to change :)

2022-11-08 13:59 UTC, lack commented on src/ctl-server.c
> +			nvnc_trace("recv: EAGAIN");
It was returning an error-but-no-details-set, which was handled properly by the caller, but I agree that this was confusing.  I'll retool this so it's more clear.

2022-11-08 20:17 UTC, lack commented on README.md
> +Use the `wayvncctl` utility to interact with this control socket from the
This one is in README.md which is markdown and should be okay?

2022-11-08 20:30 UTC, any1 commented
Hah. Sorry about that. I reviewed this while drinking the morning coffee.
I'll blame it on lack of caffeine. ;)

2022-11-09 11:01 UTC, any1 commented on README.md
> +Use the `wayvncctl` utility to interact with this control socket from the
Hah. Sorry about that. I reviewed this while drinking the morning coffee.
I'll blame it on lack of caffeine. ;)

2022-11-09 14:24 UTC, lack commented
Okay!  Tested most code paths with valgrind and fixed some refcount-based leaks.

@any1 : ready for another review!

2022-11-09 22:38 UTC, any1 reviewed
LGTM after a few final tweaks.

2022-11-09 22:38 UTC, any1 commented on src/util.c
> + * Copyright (c) 2019 - 2022 Andri Yngvason
Maybe you want to put your name here?

2022-11-09 22:38 UTC, any1 commented on src/ctl-server.c
> +	switch(cmd_type) {
Nit: style

2022-11-09 22:38 UTC, any1 commented on src/ctl-client.c
> +		struct jsonipc_request*  request,
Nit: extra space

2022-11-09 22:38 UTC, any1 commented on src/ctl-server.c
> +	struct cmd_response* resp = cmd_response_new(-1, json_pack("{s:o}",
This results in `wayvncctl` returning -1 from main, which becomes 255. Like, if you do `./build/wayvncctl set-output --switch-to=BS; echo $?`

2022-11-10 00:36 UTC, lack commented on src/ctl-server.c
> +	struct cmd_response* resp = cmd_response_new(-1, json_pack("{s:o}",
I think that's okay.  Really any non-zero code should be fine.

Would you prefer `1`?

2022-11-10 05:11 UTC, lack commented
@any1 Done!

Also fixed a handful of `char *foo` => `char* foo` we both missed :)

2022-11-10 10:44 UTC, any1 commented on src/ctl-server.c
> +	struct cmd_response* resp = cmd_response_new(-1, json_pack("{s:o}",
Well, in other places you're using `errno` codes, so this is of the wrong "type".

Also, there is some lore regarding return codes from shell scripts, which this isn't of course, and there doesn't seem to be any standard. See e.g. https://tldp.org/LDP/abs/html/exitcodes.html.

However, `man 3 exit` simply states the following:
> The exit() function causes normal process termination and the least significant byte of status (i.e., status & 0xFF) is returned  to  the  parent  (see wait(2)).

and
> The  C  standard  specifies two constants, EXIT_SUCCESS and EXIT_FAILURE, that may be passed to exit() to indicate successful or unsuccessful termination, respectively.

... which doesn't really place any constraints.

Also, I do wonder if `errno` is right for this. Maybe it's better if we define our own error codes with associated error messages, which makes the error string passed with the message redundant (because it can be found with a lookup).

Anyway, this is ok as is for now as long as we use error codes consistently; i.e. all of the same type.

2022-11-10 18:03 UTC, merged

2022-11-10 18:03 UTC, any1 commented
Thanks!