Remove the help command from wayvncctl
any1/wayvnc pull request #216
Opened 2023-01-06 18:44 UTC by lack

- Remove 'help' command and clean up help output
- Add help text for wayvncctl-only events
- Refactor option-parser table printing code for reuse
- Add command and event details to help output

Fixes #213

2023-01-07 09:45 UTC, any1 requested changes

2023-01-07 09:45 UTC, any1 commented on src/table-printer.c
> + * Copyright (c) 2022 Andri Yngvason, Jim Ramsay
The year is 2023. It's better to split this into two lines.

2023-01-07 09:45 UTC, any1 commented on src/ctl-client.c
> +#define SET_MAXLEN(accumulator, string) { \
I'm not a fan of this macro.

Consider using something like this instead:
```
accumulator = MAX(accumulator, strlen(string));
```

2023-01-07 09:45 UTC, any1 commented on src/ctl-client.c
> +			SET_MAXLEN(max_namelen, info->params[i].name);
Please, try to add some vertical spacing where it aides readability.

2023-01-07 09:45 UTC, any1 commented on src/wayvncctl.c
> +"    Connects to and interacts with a running wayvnc instance.";
I'm not sure that I agree that this should be indented.

2023-01-07 09:45 UTC, any1 commented on src/ctl-client.c
> +	struct table_printer printer = {
This is defined the same way 3 times. `max_width`, `left_indent` and `column_offset` should be defined in one place.

2023-01-07 09:45 UTC, any1 commented on src/table-printer.c
> +	char buf[80];
In the public interface of this class, this number is adjustable. Better make this oversized and add an assert to ensure that `sizeof(buf) > self->max_width + 2`. 256 should suffice.

2023-01-07 21:15 UTC, lack commented on src/table-printer.c
> +	char buf[80];
This buffer is only for the left column, so I figured even for very wide displays, 80 chars for the left-part (command name, event name, option short+long name), 80 is pretty generous...

2023-01-08 01:39 UTC, lack commented on src/table-printer.c
> +			assert(dst[last_space_pos] != '\n');
Adding this assert stops an infinite loop in the unit test for width=4

2023-01-08 01:39 UTC, lack commented on src/table-printer.c
> +			break;
moving the loop break here prevents an off-by-one error if the end of `src` is one character longer than `width` (unit test with width=17)

2023-01-08 09:07 UTC, lack commented
@any1 : Ready for re-review any time!

Also added unit tests for the reflow and table printing code which exposed a couple edge cases (also fixed).

2023-01-08 12:01 UTC, any1 requested changes

2023-01-08 12:16 UTC, lack commented on test/table-printer-test.c
> +	stream = open_memstream(&buf, &len);
Cleaner for testing, maybe, but the API becomes a chore of managing buffers then.

2023-01-08 12:51 UTC, lack commented on src/ctl-client.c
> +#define INIT_PRINTER(left_width_) { \
An init function makes sense... Then the option-parser could call the same function, as we would want everything to share the same defaults.

2023-01-08 16:04 UTC, any1 commented on src/ctl-client.c
> +#define INIT_PRINTER(left_width_) { \
Yes

2023-01-08 16:14 UTC, any1 commented on test/table-printer-test.c
> +	stream = open_memstream(&buf, &len);
One way to do it would be to expose a function that only does the formatting, which is then used by the function that does the printing. The formatting function would then be the one that's tested. Anyway, it was just a thought. This is good enough as is.

2023-01-08 16:24 UTC, lack commented
@any1 Ready for re-re-review ;)

2023-01-08 16:43 UTC, any1 approved these changes
LGTM

2023-01-08 16:43 UTC, any1 commented on src/table-printer.c
> +static struct table_printer defaults = {
Nit: This could be made const

2023-01-08 16:43 UTC, any1 commented on src/table-printer.c
> +struct table_printer* table_printer_new(FILE* stream, int left_width)
Nit: There is no need for this to be dynamically allocated. `table_printer_init` would be enough.

2023-01-08 17:21 UTC, lack commented on src/table-printer.c
> +static struct table_printer defaults = {
Not if I want table_printer_set_defaults to work as it is now.

Arguable if that's actually what we want, I guess ;)

2023-01-08 17:22 UTC, lack commented on src/table-printer.c
> +struct table_printer* table_printer_new(FILE* stream, int left_width)
Fair. And that would make the destroy unneeded.

I think I'll do that and then merge this.

2023-01-08 17:42 UTC, merged