Add basic clipboard support
any1/wayvnc pull request #66
Opened 2020-09-16 22:19 UTC by soreau

Uses wlr-data-control-unstable-v1 protocol to interface with the clipboard
making copy/paste of text possible.

2020-09-18 14:17 UTC, any1 requested changes

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +	struct data_control* self = (struct data_control*) data;
typecasting is redundant here. This occurs also in other places in this PR.

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +	FILE *mem_fp;
Star is in the wrong side.

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +	while (read(pipe_fd[0], &c, 1) > 0)
Also, what happens if `errno == EINTR`?

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +	data_control_device_offer,
prefer named field initialisers.

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +	data_control_offer
also missing name of field

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +		write(fd, d++, 1);
Why not just `write(fd, d, len)`?

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +	char* d = self->cb_data;
maybe `assert(d)`?

2020-09-18 14:17 UTC, any1 commented on src/data-control.c
> +	self->data_control_source = zwlr_data_control_manager_v1_create_data_source(self->manager);
There's an error check missing here, I think.

2020-09-18 20:44 UTC, soreau commented on src/data-control.c
> +	self->data_control_source = zwlr_data_control_manager_v1_create_data_source(self->manager);
Check for NULL? Not sure how else to check for errors here.

2020-09-18 20:45 UTC, soreau commented on src/data-control.c
> +	while (read(pipe_fd[0], &c, 1) > 0)
On EINTR, the return value of read() should be <= 0 which means we would have stopped the read loop in this case, right?

2020-09-19 10:45 UTC, any1 commented on src/data-control.c
> +	while ((ret = read(pipe_fd[0], &buf, CHUNK_SIZE)) > 0)
Maybe the check should be `== 0`? I think that's what "EOF" means, which is what the spec says should be used.

There is an example in weston for this here: https://gitlab.freedesktop.org/wayland/weston/-/blob/master/clients/window.c#L3998-4041

Based on this example, it seems that it shouldn't be very hard to make this async.

2020-09-19 10:45 UTC, any1 commented on src/data-control.c
> +	wl_display_flush(self->wl_display);
Is a flush really needed here?

2020-09-19 10:46 UTC, any1 approved these changes

2020-09-19 20:11 UTC, soreau commented on src/data-control.c
> +	while ((ret = read(pipe_fd[0], &buf, CHUNK_SIZE)) > 0)
`while ((ret = read(pipe_fd[0], &buf, CHUNK_SIZE)) > 0)` reads until `<= 0` is returned. The code you posted doesn't show anything different than what this PR does than destroy the offer on `read == 0`. In this PR, we simply destroy the offer as the spec indicates [here](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-data-control-unstable-v1.xml#L152).

2020-09-19 20:38 UTC, soreau commented on src/data-control.c
> +	while ((ret = read(pipe_fd[0], &buf, CHUNK_SIZE)) > 0)
I see that you want to poll the fd and read it when it becomes readable. Doing this requires a lot more work and code, which I am not willing to do.

2020-09-19 20:42 UTC, any1 commented on src/data-control.c
> +	while ((ret = read(pipe_fd[0], &buf, CHUNK_SIZE)) > 0)
Ok, let's just leave it as is for now, and I'll make it async before next release. Thanks for your work!

2020-09-19 21:19 UTC, any1 commented on src/data-control.c
> +	zwlr_data_control_manager_v1_destroy(self->manager);
Whoops, there's a double free of self->manager. First here...

2020-09-19 21:19 UTC, any1 commented on src/main.c
> +		zwlr_data_control_manager_v1_destroy(self->data_control.manager);
... and then here

2020-09-20 03:49 UTC, soreau commented on src/main.c
> +		zwlr_data_control_manager_v1_destroy(self->data_control.manager);
Thanks for finding this, should be fixed now. It also should work on sway too now, because I added a blatant hack to workaround the protocol bug.

2020-09-20 12:02 UTC, any1 commented
I did manage to copy some text from my vnc client after the latest changes, but when I tried to copy text into the vnc client, wayvnc stalled completely. The workaround for the wlroots issue seems racy, so that might be what went wrong for me. Maybe we should focus on solving https://github.com/swaywm/wlroots/issues/2406 first.

2020-09-22 20:09 UTC, merged

2020-09-22 20:10 UTC, any1 commented
Thanks!