PAM Authentication
any1/wayvnc pull request #72
Opened 2020-10-16 18:55 UTC by NickSica

Adds barebones PAM authentication.

2020-10-17 13:38 UTC, any1 requested changes
How does this work? Can any user log in with their own credentials, or do they need to be a part of some group or something?

2020-10-17 13:38 UTC, any1 commented on meson.build
> +if libpam.found()
Don't you need to check for `libpam_misc` too?

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +#include <security/pam_appl.h>
Missing `#ifdef ENABLE_PAM`

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +        const char *user;
Style: This project uses tabs for indentation. The `*` should be on the left side.

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +static int pam_return_pwd(int num_msg, const struct pam_message **msgm, struct pam_response **response, void *appdata_ptr)
Style: Stars should be on the left side and the line length should not exceed 80 characters.

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +    struct credentials *cred = (struct credentials *) appdata_ptr;
Typecasting is redundant for void pointers.

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +    struct pam_response *resp = (struct pam_response *)malloc(sizeof(struct pam_response) * num_msg);
Typecasting is not needed for malloc. Prefer `calloc(sizeof(*resp), num_msg)`.

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +    for(int i = 0; i < num_msg; i++)
Style: Use tabs, `{` should be inline except in function declarations. There should be a space between `for` and `(`; i.e. `for (int i = 0; i < num_msg; i++) {`

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +        switch(msgm[i]->msg_style)
Ditto

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +#ifdef ENABLE_PAM
Enabling PAM should be a config and/or command line option. If a package is built and released with PAM enabled it will break authentication for current users if done like this, so it needs to be an opt-in.

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +        if((result = pam_start(service, username, &conv, &pamh)) != PAM_SUCCESS)
I think you need to call `pam_end()` somewhere. Otherwise the handle is leaked.

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +        else if((result = pam_authenticate(pamh, PAM_SILENT|PAM_DISALLOW_NULL_AUTHTOK)) != PAM_SUCCESS)
`else` is redundant, due to `return` above.

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +        else if((result = pam_acct_mgmt(pamh, 0)) != PAM_SUCCESS)
ditto

2020-10-17 13:38 UTC, any1 commented on src/main.c
> +            fprintf(stderr, "PAM account management failed: %d\n", result);
There's a function in wayvnc called `log_error` which serves this purpose.

2020-10-17 20:28 UTC, NickSica commented
> How does this work? Can any user log in with their own credentials, or do they need to be a part of some group or something?
The wayvnc.pam file needs to be placed in /etc/pam.d/ and defines how authentication for the service is done. This passes the authentication request onto PAM. In theory you could restrict it to groups or pass it to something like LDAP and only need to change the config to do so but my barebones version just authenticates the user.

I'll fix the style changes, I already fixed most of the other errors but forgot to push it to the pull request last night.

2020-10-18 18:58 UTC, NickSica commented on meson.build
> +if libpam.found()
I'm not exactly sure if one can ever come without the other, but I'll check for both.

2020-10-18 20:13 UTC, NickSica commented on src/main.c
> +#include <security/pam_appl.h>
Trying to wrap it with the ifdef seemed to break other stuff even though the other stuff was wrapped as well.

2020-10-18 20:14 UTC, NickSica commented
Since it is in the config file now, I didn't know if you wanted to just get rid of the ENABLE_PAM in the build config or not. People would have to have pam on their system to build it, but I think most do already.

2020-10-19 19:44 UTC, any1 requested changes

2020-10-19 19:44 UTC, any1 commented on src/main.c
> +#include <security/pam_appl.h>
You probably need to include at a later point where "config.h" has been included. It should be included here explicitly, but I guess it's included by some other header.

2020-10-19 19:44 UTC, any1 commented on src/main.c
> +    struct credentials* cred = appdata_ptr;
There are still some spaces in this PR which should be tabs.

2020-10-19 19:44 UTC, any1 commented on src/main.c
> +	switch(msgm[i]->msg_style)
Style: `{` should be inline.

2020-10-19 19:44 UTC, any1 commented on src/main.c
> +    struct pam_response* resp = calloc(sizeof(*response), num_msg);
Where is this freed?

2020-10-19 19:44 UTC, any1 commented on src/main.c
> +	    struct credentials cred = { strdup(username), strdup(password) };
Where are these freed?

It would be nicer to have this code block within this `if` extracted to a function.

2020-10-19 19:44 UTC, any1 commented on src/main.c
> +#ifdef ENABLE_PAM
You can avoid this `#ifdef` by doing an early return in the pam case. I strongly prefer early returns in general.

2020-10-22 22:55 UTC, NickSica commented on src/main.c
> +    struct pam_response* resp = calloc(sizeof(*response), num_msg);
this gets assigned to pam_response which gets handled further by pam I think. I'm guessing a pam internal function frees it but I'm not 100% sure. I can't free it there because it is used by pam internally.

2020-10-28 17:52 UTC, NickSica commented
I don't know if you get notified of new commits, but I pushed the changes you requested.

2020-10-28 18:27 UTC, any1 commented
> I don't know if you get notified of new commits, but I pushed the changes you requested.

Yeah, sorry, I spent half a day last weekend trying to figure out if there was some alternate route to using the conversation function like this because it feels like a dirty hack and not at all how it was intended to be used.

There's also an issue with this that a failed login will cause a delay in the main loop and this halts all events for the duration of the delay, which can be a few seconds. In the best case, this causes frustration and in the worst case, it makes a DoS attack very easy. I'm afraid that if we want to go this hacky route, then we need to run authentication in a worker thread.

2020-10-28 20:09 UTC, NickSica commented
> > I don't know if you get notified of new commits, but I pushed the changes you requested.
> 
> Yeah, sorry, I spent half a day last weekend trying to figure out if there was some alternate route to using the conversation function like this because it feels like a dirty hack and not at all how it was intended to be used.
> 
> There's also an issue with this that a failed login will cause a delay in the main loop and this halts all events for the duration of the delay, which can be a few seconds. In the best case, this causes frustration and in the worst case, it makes a DoS attack very easy. I'm afraid that if we want to go this hacky route, then we need to run authentication in a worker thread.

Hey no problem! Really? I kind of used tigervnc code as a reference for this implementation so it's interesting it's hacky.

2020-11-01 17:38 UTC, any1 commented
I guess this is as good as it gets with the PAM API being the way it is. Can you move this into its own source file? At least that way, we can keep things a little bit neater.

The delay issue that I mentioned can be worked around by using the `nodelay` option in the PAM config file, but in that case, it might be a good idea to add a timer that inhibits login attempts to make brute force attacks harder.

2020-11-02 14:48 UTC, NickSica commented
> I guess this is as good as it gets with the PAM API being the way it is. Can you move this into its own source file? At least that way, we can keep things a little bit neater.
> 
> The delay issue that I mentioned can be worked around by using the `nodelay` option in the PAM config file, but in that case, it might be a good idea to add a timer that inhibits login attempts to make brute force attacks harder.

Ok I made the changes requested, let me know if there are any issues.

2020-11-02 16:08 UTC, any1 requested changes
Modifying .gitignore should be a separate commit. See https://chris.beams.io/posts/git-commit/

2020-11-02 16:08 UTC, any1 commented on src/pam_auth.c
> +	if ((result = pam_end(pamh, result)) != PAM_SUCCESS) {
You don't need to check the result of this. `pam_end` only returns error if `pamh == NULL`, which should not be the case.

2020-11-02 16:08 UTC, any1 commented on src/pam_auth.c
> +	if ((result = pam_start(service, username, &conv, &pamh)) != PAM_SUCCESS) {
It's nicer to not mix the assignment and the error check. I'd rather like to see:
```
result = pam_start(...)
if (result != PAM_SUCCESS) {...
```
this comment also applies for the error checks below.

2020-11-02 16:38 UTC, NickSica commented on src/pam_auth.c
> +			resp[i].resp = strdup(cred->user);
I figured, but I wanted to be thorough. I'll take out the extra stuff though.

2020-11-02 16:41 UTC, NickSica commented on src/pam_auth.c
> +			free(resp);
I read somewhere the response structure is freed by PAM in a different function if authentication is successful. If it isn't we have to free it which is what is happening here. That might be a different version of PAM though and not the linux version. Let me play around with this to see.

2020-11-02 16:48 UTC, any1 commented on src/pam_auth.c
> +			free(resp);
Yes, that's what I read too. What I'm commenting on is that if there is an error that occurs, it's not enough to do `free(resp)`, you also need to free `resp[i].resp` for each `i`.

2020-11-02 16:49 UTC, NickSica commented on src/pam_auth.c
> +			free(resp);
Oh gotcha, I'll add that in.

2020-11-02 16:49 UTC, NickSica commented
> Modifying .gitignore should be a separate commit. See https://chris.beams.io/posts/git-commit

> Modifying .gitignore should be a separate commit. See https://chris.beams.io/posts/git-commit/

What would be the best way to split these using git? My git knowledge is very basic

2020-11-02 16:56 UTC, any1 commented
> > Modifying .gitignore should be a separate commit. See [chris.beams.io/posts/git-commit](https://chris.beams.io/posts/git-commit)
> 
> What would be the best way to split these using git? My git knowledge is very basic

We can do that at the end with `git rebase --interactive`. Then we'll squash the commits that add pam into one and split out the .gitignore one.

2020-11-02 16:58 UTC, NickSica commented
> > > Modifying .gitignore should be a separate commit. See [chris.beams.io/posts/git-commit](https://chris.beams.io/posts/git-commit)
> > 
> > 
> > What would be the best way to split these using git? My git knowledge is very basic
> 
> We can do that at the end with `git rebase --interactive`. Then we'll squash the commits that add pam into one and split out the .gitignore one.

Ok, thank you for the patience. This is the first open source project I've contributed to.

2020-11-02 17:15 UTC, NickSica commented on include/pam_auth.h
> +#include <stdlib.h>
I get implicit declaration warnings when I remove the includes that you recommended to remove.

2020-11-02 17:17 UTC, NickSica commented on include/pam_auth.h
> +#include <stdlib.h>
Nevermind I think I misunderstood the comments you wanted me to move everything except stdbool.h into the .c file. I moved stdbool.h into the .c and removed the others.

2020-11-02 17:21 UTC, NickSica commented
Ok that should resolve all your comments

2020-11-02 17:46 UTC, any1 reviewed
Almost there!

2020-11-02 17:46 UTC, any1 commented on src/pam_auth.c
> +		goto error;
Here you can just return false;

2020-11-02 17:46 UTC, any1 commented on src/pam_auth.c
> +	free(pamh);
`pam_end` is used to free `pamh`.

2020-11-02 17:46 UTC, any1 commented on src/pam_auth.c
> +
Put `error:` here and instead of `return true` do `return result == PAM_SUCCESS`?

2020-11-02 17:46 UTC, any1 commented on src/pam_auth.c
> +
Hehe, there's a lot of trailing newlines at the end of this file.

2020-11-02 17:46 UTC, any1 commented on wayvnc.pam
> +auth    required pam_unix.so nodelay deny=3 unlock_time=600
This seems like a good solution.

2020-11-02 18:06 UTC, NickSica commented on src/pam_auth.c
> +
Oh sorry I've been putting off adding something to auto-trim them in my editor

2020-11-02 18:10 UTC, NickSica commented on src/pam_auth.c
> +
I'm not 100% sure if I understood this comment correctly but check the latest.

2020-11-02 18:25 UTC, any1 commented on src/pam_auth.c
> +
I meant to put the `error:` tag above the call to `pam_end`.

2020-11-02 18:26 UTC, NickSica commented on src/pam_auth.c
> +
whoops! I'll fix that haha

2020-11-02 18:36 UTC, any1 commented on src/pam_auth.c
> +		log_error("ERROR: PAM start failed: %d\n", result);
Sorry, I keep noticing new things. It's probably nicer to give the user a readable error message. `pam_strerror(result)` should do that.

LGTM otherwise. Do you want to have a go a rebasing?

2020-11-02 20:31 UTC, NickSica commented on src/pam_auth.c
> +		log_error("ERROR: PAM start failed: %d\n", result);
Sure haha how do you wanna do this?

2020-11-02 20:38 UTC, NickSica commented on src/pam_auth.c
> +		log_error("ERROR: PAM start failed: %d\n", result);
If I attempt to pass pam_strerror to wayvnc's log error function, there are some issues. Should I print directly to stderr?

2020-11-02 20:50 UTC, any1 commented on src/pam_auth.c
> +		log_error("ERROR: PAM start failed: %d\n", result);
Works fine on my system...
```
[andri@galago wayvnc]$ git diff
diff --git a/src/pam_auth.c b/src/pam_auth.c
index 4ff69de..3d4b595 100644
--- a/src/pam_auth.c
+++ b/src/pam_auth.c
@@ -46,7 +46,7 @@ bool pam_auth(const char* username, const char* password)
        pam_handle_t* pamh;
        int result = pam_start(service, username, &conv, &pamh);
        if (result != PAM_SUCCESS) {
-               log_error("ERROR: PAM start failed: %d\n", result);
+               log_error("ERROR: PAM start failed: %s\n", pam_strerror(pamh, result));
                return false;
        }
```

2020-11-02 21:15 UTC, NickSica commented on src/pam_auth.c
> +		log_error("ERROR: PAM start failed: %d\n", result);
There we go should be good now

2020-11-03 20:39 UTC, NickSica commented
This should be good to go correct? Sorry I'm not sure what you get notified about.

2020-11-03 21:53 UTC, any1 commented
Ahh, there's one more thing. The new files are missing license & copyright.

2020-11-03 21:55 UTC, NickSica commented
> Ahh, there's one more thing. The new files are missing license & copyright.

Should I copy the copyright you have in the files and replace your name with mine?

2020-11-03 21:59 UTC, any1 commented
> > Ahh, there's one more thing. The new files are missing license & copyright.
> 
> Should I copy the copyright you have in the files and replace your name with mine?

Yes, that will do

2020-11-03 22:04 UTC, NickSica commented
> > > Ahh, there's one more thing. The new files are missing license & copyright.
> > 
> > 
> > Should I copy the copyright you have in the files and replace your name with mine?
> 
> Yes, that will do

Done

2020-11-03 22:22 UTC, any1 approved these changes

2020-11-03 22:24 UTC, NickSica commented
Do you have to do all the rebasing or do I do it?

2020-11-03 22:24 UTC, any1 commented
I did a behind-the-scenes merge. See https://github.com/any1/wayvnc/commit/6a73f293fc60e9297695f196ba709cc3e60e12af

Thanks!

2020-11-03 22:24 UTC, closed without merging

2020-11-03 23:31 UTC, any1 commented
By the way, in case you're looking for more things to do, it would be nice to have PAM usage documented in the man page.

2020-11-03 23:33 UTC, NickSica commented
If I get more free time, I'd be glad to help out. School is keeping me pretty busy as is, though.